$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$TauriDir = Resolve-Path (Join-Path $ScriptDir "..")
$BundleDir = Join-Path $TauriDir "resources\markitdown"
$BinDir = Join-Path $BundleDir "bin"
$BuildDir = Join-Path $TauriDir "target\markitdown-build"
$VenvDir = Join-Path $BuildDir "venv"
$PythonBin = if ($env:PYTHON_BIN) { $env:PYTHON_BIN } else { "python" }
$AppName = "openwiki-markitdown"

New-Item -ItemType Directory -Force -Path $BinDir, $BuildDir | Out-Null

$VenvPython = Join-Path $VenvDir "Scripts\python.exe"
if (!(Test-Path $VenvPython)) {
  & $PythonBin -m venv $VenvDir
}

& $VenvPython -m pip install --upgrade pip
& $VenvPython -m pip install --upgrade pyinstaller "markitdown[pdf,docx,pptx]"

$ExePath = Join-Path $BinDir "$AppName.exe"
Remove-Item -Force -ErrorAction SilentlyContinue $ExePath

$PyInstaller = Join-Path $VenvDir "Scripts\pyinstaller.exe"
& $PyInstaller `
  --clean `
  --onefile `
  --name $AppName `
  --collect-data magika `
  --distpath $BinDir `
  --workpath (Join-Path $BuildDir "pyinstaller-work") `
  --specpath (Join-Path $BuildDir "pyinstaller-spec") `
  (Join-Path $ScriptDir "markitdown_converter.py")

$TestDoc = Join-Path $env:TEMP "openwiki-markitdown-smoke.txt"
$SmokeOut = Join-Path $env:TEMP "openwiki-markitdown-smoke.out"
$SmokeErr = Join-Path $env:TEMP "openwiki-markitdown-smoke.err"
[System.IO.File]::WriteAllText(
  $TestDoc,
  "OpenWiki MarkItDown smoke test`n中文烟测",
  [System.Text.UTF8Encoding]::new($false)
)
$SmokeProcess = Start-Process `
  -FilePath $ExePath `
  -ArgumentList @($TestDoc) `
  -NoNewWindow `
  -Wait `
  -PassThru `
  -RedirectStandardOutput $SmokeOut `
  -RedirectStandardError $SmokeErr
if ($SmokeProcess.ExitCode -ne 0) {
  $SmokeError = if (Test-Path $SmokeErr) { Get-Content -Raw -Encoding UTF8 $SmokeErr } else { "" }
  throw "MarkItDown smoke test failed with exit code $($SmokeProcess.ExitCode). $SmokeError"
}
$SmokeOutput = Get-Content -Raw -Encoding UTF8 $SmokeOut
if ($SmokeOutput -notmatch "OpenWiki MarkItDown smoke test") {
  throw "MarkItDown smoke test did not return the expected text"
}
Remove-Item -Force -ErrorAction SilentlyContinue $TestDoc, $SmokeOut, $SmokeErr

@"
Generated by scripts/setup_markitdown.ps1
Python: $(& $VenvPython --version 2>&1)
MarkItDown: $(& $VenvPython -m pip show markitdown | Select-String '^Version: ' | ForEach-Object { $_.ToString().Split(':', 2)[1].Trim() })
PyInstaller: $(& $PyInstaller --version)
"@ | Set-Content -Path (Join-Path $BundleDir "VERSION.txt") -Encoding UTF8

Write-Host "MarkItDown converter ready at $ExePath"
