#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TAURI_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
BUNDLE_DIR="${TAURI_DIR}/resources/markitdown"
BIN_DIR="${BUNDLE_DIR}/bin"
BUILD_DIR="${TAURI_DIR}/target/markitdown-build"
VENV_DIR="${BUILD_DIR}/venv"
PYTHON_BIN="${PYTHON_BIN:-python3}"
APP_NAME="openwiki-markitdown"

mkdir -p "${BIN_DIR}" "${BUILD_DIR}"

if [ ! -x "${VENV_DIR}/bin/python" ]; then
  "${PYTHON_BIN}" -m venv "${VENV_DIR}"
fi

"${VENV_DIR}/bin/python" -m pip install --upgrade pip
"${VENV_DIR}/bin/python" -m pip install --upgrade pyinstaller 'markitdown[pdf,docx,pptx]'

rm -f "${BIN_DIR}/${APP_NAME}"

"${VENV_DIR}/bin/pyinstaller" \
  --clean \
  --onefile \
  --name "${APP_NAME}" \
  --collect-data magika \
  --distpath "${BIN_DIR}" \
  --workpath "${BUILD_DIR}/pyinstaller-work" \
  --specpath "${BUILD_DIR}/pyinstaller-spec" \
  "${SCRIPT_DIR}/markitdown_converter.py"

TEST_DOC="$(mktemp)"
printf 'OpenWiki MarkItDown smoke test\n中文烟测\n' > "${TEST_DOC}"
SMOKE_OUTPUT="$("${BIN_DIR}/${APP_NAME}" "${TEST_DOC}")"
if [[ "${SMOKE_OUTPUT}" != *"OpenWiki MarkItDown smoke test"* ]]; then
  echo "MarkItDown smoke test did not return the expected text" >&2
  exit 1
fi
rm -f "${TEST_DOC}"

cat > "${BUNDLE_DIR}/VERSION.txt" <<EOF
Generated by scripts/setup_markitdown.sh
Python: $("${VENV_DIR}/bin/python" --version 2>&1)
MarkItDown: $("${VENV_DIR}/bin/python" -m pip show markitdown | awk -F': ' '/^Version: / { print $2 }')
PyInstaller: $("${VENV_DIR}/bin/pyinstaller" --version)
EOF

echo "MarkItDown converter ready at ${BIN_DIR}/${APP_NAME}"
